#pragma once
#include "framework/include/Widget/Traits/IKeyboardListener.h"
#include "framework/include/Widget/Traits/IMouseAccessible.h"
#include "framework/include/Widget/Traits/IMouseClickable.h"
#include "framework/include/Widget/Traits/IMouseHoldable.h"
#include "framework/include/Widget/Traits/IMouseSelectable.h"
#include "framework/include/Widget/Traits/Widget.h"
#include "framework/include/Widget/Traits/RectangleWidget.h"
#include "framework/include/Widget/Traits/IScrollable.h"