#pragma once
#include "Traits/IKeyboardListener.h"
#include "Traits/IMouseAccessible.h"
#include "Traits/IMouseClickable.h"
#include "Traits/IMouseHoldable.h"
#include "Traits/IMouseSelectable.h"
#include "Traits/Widget.h"
#include "Traits/RectangleWidget.h"
#include "Traits/IScrollable.h"